### ISSUE TITLE
Build failures with GitHub Pages

### ISSUE THREAD

**Issue by lastmjs** [earaujoassis/ubuntu-fontface#8] opened 2016-02-12 04:32 UTC
I'm not sure if this is just a GitHub Pages problem, but when I use the library and push to GitHub Pages, the build fails until I remove this file: 'ubuntu-fontface-master/site/css/ubuntu-fontface-site.scss'.

Here is the error from GitHub pages:

    The page build failed with the following error:

    The file `www/node_modules/ubuntu-fontface-master/site/css/ubuntu-fontface-site.scss` contains       syntax errors. For more information, see https://help.github.com/articles/page-build-failed-markdown-errors.

**Comment by earaujoassis** [comment] 2016-06-13 22:51
@lastmjs I know that is old, but do you have any clue on how to reproduce that problem? Is that still valid? Thank you. Best,

**Comment by earaujoassis** [comment] 2016-06-19 20:49
I'm closing this, since I was not able to replicate locally.

**Closed by earaujoassis** 2016-06-19 20:49 UTC
Labels: bug
